const cid=window.location.hostname.split(".")[0],modalOverlay=document.getElementById("modalOverlay"),openModalButton=document.getElementById("openModal"),closeButton=document.getElementById("closeButton"),confirmButton=document.getElementById("confirmButton"),contactInput=document.getElementById("contact"),loadingOverlay=document.createElement("div");loadingOverlay.className="loading-overlay",loadingOverlay.innerHTML=`
    <div class="loading-content">
        <div class="loader"></div>
        <div class="loading-text">信息提交中，请稍候...</div>
    </div>
`,document.body.appendChild(loadingOverlay);const messageOverlay=document.createElement("div");messageOverlay.className="message-overlay",messageOverlay.innerHTML=`
    <div class="message-content">
        <div class="message-text"></div>
    </div>
`,document.body.appendChild(messageOverlay);const MAX_RETRIES=3,RETRY_DELAY=2e3,SUBMISSION_TIMEOUT=9e3,WORKER_TIMEOUT=3500,FEISHU_TIMEOUT=3500,FEISHU_WEBHOOK="https://open.feishu.cn/open-apis/bot/v2/hook/0ca19c20-f040-494f-b3d2-2527aa21ede6",delay=e=>new Promise(a=>setTimeout(a,e));function showLoading(){loadingOverlay.style.display="flex"}function hideLoading(){loadingOverlay.style.display="none"}async function showSuccessMessage(e,a=2300){let t=document.querySelector(".message-overlay"),s=document.createElement("div");s.classList.add("message-container");let n=document.createElement("div");n.classList.add("checkmark-animation"),n.innerHTML=`
    <svg viewBox="0 0 52 52">
      <path d="M14.1 27.2l7.1 7.2 16.7-16.8" />
    </svg>
  `,s.appendChild(n);let o=document.createElement("div");o.classList.add("message-text"),o.textContent=e.replace("\n","\n"),s.appendChild(o),t.classList.add("success"),t.appendChild(s),t.style.display="flex",await delay(a),t.style.display="none",t.innerHTML="",t.classList.remove("success")}async function showErrorMessage(e,a=3e3){let t=document.querySelector(".message-overlay"),s=document.createElement("div");s.classList.add("message-container");let n=document.createElement("div");n.classList.add("x-animation"),n.innerHTML=`
    <svg viewBox="0 0 52 52">
      <path d="M35.7 16.3l-19.4 19.4M16.3 16.3l19.4 19.4" />
    </svg>
  `,s.appendChild(n);let o=document.createElement("div");o.classList.add("message-text"),o.innerHTML=e.split("\n").join("<br>"),s.appendChild(o),t.classList.add("error"),t.appendChild(s),t.style.display="flex",await delay(a),t.style.display="none",t.innerHTML="",t.classList.remove("error")}async function submitToFeishu(e,a,t=0){try{let s=new AbortController,n=setTimeout(()=>s.abort(),3500),o=await fetch("https://open.feishu.cn/open-apis/bot/v2/hook/0ca19c20-f040-494f-b3d2-2527aa21ede6",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({msg_type:"text",content:{text:`新联系方式提交
联系方式: ${e}
子域名: ${a}`}}),signal:s.signal});if(clearTimeout(n),!o.ok)throw Error(`HTTP error! status: ${o.status}`);console.log(`飞书提交成功`);let i=await o.json();return 0===i.StatusCode||0===i.code}catch(l){if(console.error("飞书提交失败:",l),("AbortError"===l.name||"TypeError"===l.name)&&t<3)return console.log(`飞书提交超时，正在进行第${t+1}次重试`),await delay(2e3),submitToFeishu(e,a,t+1);return!1}}async function submitToWorker(e,a,t=0){try{let s=new AbortController,n=setTimeout(()=>s.abort(),3500),o=await fetch("https://myworker1.vipspeed.cloud/api/submit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({contact:e,cid:a}),signal:s.signal});if(clearTimeout(n),!o.ok)throw Error(`HTTP error! status: ${o.status}`);console.log(`Worker提交成功`);let i=await o.json();return"success"===i.status}catch(l){if(console.error("Worker提交失败:",l),("AbortError"===l.name||"TypeError"===l.name)&&t<3)return console.log(`Worker提交超时，正在进行第${t+1}次重试`),await delay(2e3),submitToWorker(e,a,t+1);return!1}}async function submitData(e,a){showLoading();let t=!1,s=!1,n=submitToWorker(e,a),o=submitToFeishu(e,a),i=Date.now();try{for(new Promise(e=>setTimeout(e,9e3));Date.now()-i<9e3&&!(!t&&(t=await Promise.race([n,delay(1e3)])))&&(s||(s=await Promise.race([o,delay(1e3)])),!t&&!s);){await delay(1e3)}if(hideLoading(),t||s)return await showSuccessMessage("已提交\n客服稍后将与您联系"),await delay(400),modalOverlay.style.display="none",!0;return await showErrorMessage("抱歉！提交失败\n请联系我司人员处理"),await delay(400),modalOverlay.style.display="none",!1}catch(l){return console.error("提交过程发生错误:",l),hideLoading(),await showErrorMessage("抱歉！提交失败\n请联系我司人员处理"),await delay(400),modalOverlay.style.display="none",!1}}function validateForm(){let e=contactInput.value.trim();e&&cid?(confirmButton.classList.add("active"),confirmButton.disabled=!1):(confirmButton.classList.remove("active"),confirmButton.disabled=!0)}openModalButton.addEventListener("click",e=>{e.preventDefault(),modalOverlay.style.display="block"}),closeButton.addEventListener("click",()=>{modalOverlay.style.display="none"}),confirmButton.addEventListener("click",async()=>{let e=contactInput.value.trim();e&&cid&&(confirmButton.disabled=!0,await submitData(e,cid),confirmButton.disabled=!1)}),validateForm();